### ISSUE TITLE
Can onNetError messages be a promise rejection instead as part of the method call?

### ISSUE THREAD

**Issue by theogravity** [victorquinn/memcache-plus#15]
I'm trying to port my `memcached` code over to `memcached-plus`, and it does not seem that the  commands reject when there are server issues, and instead `onNetError` seems to be the catch-all.

The problem I'm having is that the `memcached` library commands can return an error in the callback, which I generally use as part of my promise rejection. 

However, with `memcached-plus`, the lib call just hangs there, as if waiting to resolve indefinitely if I shut down the memcached server mid-transaction. My fear is that if the server is down, these promises will continue to queue up with heavy usage.  

Ideally I'd like the error to be a rejection on the promise. Is that possible to do?

Here's what I'm trying to do:

```
  function failure (reject, err) {
    // do some error handling then have a custom error be caught downstream
   // *including server net issues*

   ...
    reject(getResponseObj(DB_FAILURE))
  }
...

 // assume this is a method in my memcache client
  del (key) {
    return new Promise ((resolve, reject) => {
      this.memcached.delete(key).then(resolve).catch((err) => failure(reject, err))
    })
  }
```

**Comment by victorquinn** [comment]
Hrm, it should definitely be handled as a promise rejection, I'll investigate, apologies for any issues!

**Comment by theogravity** [comment]
Hey, no problem. Thanks for the response. Let me know if I can help; if you can point me to places where it can be implemented and you'd like me to do the work, let me know.

**Comment by Bazze** [comment]
I'm also willing to help on this if needed, please point me in the right direction. I'm about to get started using this library but won't dare to go into production without a fix for this!

**Comment by victorquinn** [comment]
Ok so this should be fixed!

Turns out the original behavior was actually to do that but it was only rejecting the Promise if the buffer got over 1000 items. I updated it so this buffer length is now configurable so you can set it to `0` and essentially get an error returned when any single message cannot be successfully written for any reason.

The intent here was that Memcache Plus could be a bit fault tolerant and handle momentary connection blips by building up a queue and then flushing it when a reconnect happens. Memcache Plus automatically does an exponential backoff and tries to reconnect on its own, so rejecting every Promise when a momentary connection blip happened would make that feature of reconnecting and then flushing that buffer kind of useless.

So, I had written it to basically detect if there is a connection issue and buffer requests, only rejecting Promises when the queue got to have more than 1000 items in it. Can't remember why I picked this default but it was hard coded in there. So it's now updated so you can configure it and, if you want, set the length to 0 causing no messages to ever be buffered and errors to be thrown the second there is a connection issue.

Anyway, to enable this, change your Memcache Plus init code to add the new option, for example:

```js
// Before, with default 1000 item buffer
var MemcachePlus = require('memcache-plus');
var client = new MemcachePlus();

// After, now will throw error and never buffer
var MemcachePlus = require('memcache-plus');
var client = new MemcachePlus({ bufferBeforeError: 0 });
```

**Comment by theogravity** [comment]
Thank you for the explanation, it definitely makes sense as to why you'd do it this way!

**Comment by theogravity** [comment]
Also may I ask for when the new npm package will be published?

**Comment by victorquinn** [comment]
Yup, shooting for 30 mins or so, currently implementing one other feature and hoping to ship them together. I'll update here when I publish to npm!

**Comment by theogravity** [comment]
Thank you!

**Comment by victorquinn** [comment]
Done! Deployed as as 0.2.10 (sorry, actually deployed about a half hour ago but forgot to update this thread)

**Comment by Bazze** [comment]
Thanks a lot. Great work!

**Comment by Bazze** [comment]
Hmm I'm not sure if this actually solves my problem. If the connection is down, we won't get to where the new `bufferBeforeError` option is used due to the [this.ready()](https://github.com/victorquinn/memcache-plus/blob/master/lib/client.js#L400) check in the run function. If the connection is down I need to get a rejection in order to circuit break correctly.

**Comment by victorquinn** [comment]
Hrm, guess I hadn't considered that case but that totally makes sense. 

Reopening this and I'll figure out a solution.

**Comment by victorquinn** [comment]
Ok, should be fixed this time and published to npm as 0.2.11.

Apologies for not fixing it entirely the first go around!

**Comment by Bazze** [comment]
Great thank you! Now it works!

Another questions, shouldn't we reject the promise with an error (e.g. `new Error('message')`)? The current implementation generates:

``````
Warning: a promise was rejected with a non-error: [object String]
     at Client.run (node_modules/memcache-plus/lib/client.js:407:24)
     at Client.set (node_modules/memcache-plus/lib/client.js:302:17)
     [...]
``````

**Comment by victorquinn** [comment]
Oof yes it should. I thought Promise.reject would automatically wrap the text in an Error. 

Apologies for all this mess, I had a hard time coming up with a solid unit test for this so I just went without a unit test and tried killing the Memcached process on my local machine when that item ran to set up the test case. Anyway, this is why this issue has been so tricky to fix cleanly. 

Fix incoming!

**Comment by victorquinn** [comment]
This new fix (wrapping the error message in an Error object) is live on npm as 0.2.12!

**Comment by Bazze** [comment]
I see! No worries, I appreciate your super quick responses. Amazing. Thanks!
