### ISSUE TITLE
Can you move chai from deps to devDeps?

### ISSUE THREAD

**Issue by theogravity** [victorquinn/memcache-plus#34]
It's usually a devDep and it's a bit odd to see it installed as part of a production install. I can understand maybe if you're going to run tests before prod is started, but if you're going to do that, you'd probably have the lib at the application level, not at this module level.

**Comment by victorquinn** [comment]
It's in there because I use its assert to kick out if the user tries to do something silly like set or delete without providing a key. Since this would never ever work I use assert from Chai for some cleaner code. Not opposed to an alternative solution but Chai worked nice and simply so I hesitate to scrap it just because it's usually a Dev dependency.

**Comment by theogravity** [comment]
understood, thanks
